package xyz.atheon.verity

/**
 * A zero-knowledge proof generated by [ProverScheme.prove].
 *
 * Wraps the raw proof bytes with convenience accessors.
 * Pass to [VerifierScheme.verify] to check validity.
 *
 * Note: This is not a `data class` because ByteArray does not have
 * structural equality — equals/hashCode are implemented manually
 * using contentEquals/contentHashCode.
 */
class Proof internal constructor(data: ByteArray) {
    /** The raw proof bytes. */
    val data: ByteArray = data.copyOf()

    /** Proof size in bytes. */
    val size: Int get() = data.size

    /** Hex-encoded proof string (full). */
    val hex: String get() = buildString(data.size * 2) {
        for (b in data) append("%02x".format(b))
    }

    /** Truncated hex string for display (first [maxBytes] bytes + "..."). */
    @JvmOverloads
    fun hexPreview(maxBytes: Int = 32): String {
        val prefix = data.take(maxBytes).joinToString("") { "%02x".format(it) }
        return if (data.size > maxBytes) "$prefix..." else prefix
    }

    /** Create a proof from raw bytes received from an external source. */
    fun toByteArray(): ByteArray = data.copyOf()

    override fun equals(other: Any?): Boolean =
        other is Proof && data.contentEquals(other.data)

    override fun hashCode(): Int = data.contentHashCode()

    override fun toString(): String = "Proof(${size} bytes)"

    companion object {
        /**
         * Create a proof from raw bytes.
         *
         * Useful for proofs received over a network or from another system.
         *
         * @param data Raw proof bytes.
         */
        @JvmStatic
        fun fromBytes(data: ByteArray): Proof {
            require(data.isNotEmpty()) { "proof data cannot be empty" }
            return Proof(data)
        }
    }
}
