import Foundation

/// A zero-knowledge proof generated by ``ProverScheme/prove(witness:)``.
///
/// Wraps the raw proof bytes with convenience accessors.
/// Pass to ``VerifierScheme/verify(proof:)`` to check validity.
public struct Proof: Sendable, Equatable, Hashable, CustomStringConvertible {
    /// The raw proof bytes.
    public let data: Data

    /// Proof size in bytes.
    public var size: Int { data.count }

    /// Pre-built hex lookup table — avoids per-byte String(format:) overhead.
    private static let hexTable: [String] = (0...255).map {
        String(format: "%02x", $0)
    }

    /// Hex-encoded proof string (full).
    public var hex: String {
        data.reduce(into: "") { $0 += Self.hexTable[Int($1)] }
    }

    /// Truncated hex string for display (first `maxBytes` bytes + "...").
    public func hexPreview(maxBytes: Int = 32) -> String {
        let prefix = data.prefix(maxBytes).map { Self.hexTable[Int($0)] }.joined()
        return data.count > maxBytes ? prefix + "..." : prefix
    }

    public init(data: Data) {
        self.data = data
    }

    public static func fromBytes(_ data: Data) -> Proof {
        Proof(data: data)
    }

    public var description: String {
        "Proof(\(size) bytes)"
    }
}
