import Foundation

/// A zero-knowledge proof generated by ``ProverScheme/prove(witness:)``.
///
/// Wraps the raw proof bytes with convenience accessors.
/// Pass to ``VerifierScheme/verify(proof:)`` to check validity.
public struct Proof: Sendable, Equatable, Hashable, CustomStringConvertible {
    /// The raw proof bytes.
    public let data: Data

    /// Proof size in bytes.
    public var size: Int { data.count }

    /// Hex-encoded proof string (full).
    public var hex: String {
        data.reduce(into: String()) { result, byte in
            result += String(format: "%02x", byte)
        }
    }

    /// Truncated hex string for display (first `maxBytes` bytes + "...").
    public func hexPreview(maxBytes: Int = 32) -> String {
        let prefix = data.prefix(maxBytes).map { String(format: "%02x", $0) }.joined()
        return data.count > maxBytes ? prefix + "..." : prefix
    }

    public init(data: Data) {
        self.data = data
    }

    public var description: String {
        "Proof(\(size) bytes)"
    }
}
